import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/sonner'
// import { Geist, Geist_Mono } from 'next/font/google'
import '@/assets/globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="w-screen h-screen overflow-hidden" lang="zh">
      <body
        className={` antialiased w-full h-full overflow-hidden`}
      >
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  )
}
