import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/sonner'
import '@/assets/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="w-screen h-screen overflow-hidden" lang="zh">
      <body
        className={` antialiased w-full h-full overflow-hidden`}
      >
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  )
}
